### ISSUE TITLE
NGC options

### ISSUE THREAD

**Issue by wartab** [jolly-roger/gulp-ngc#5]
Is there a way to add compile options to NGC? The specific use case I'm thinking of is internationalization as described here:

It requires to pass arguments such as those:
`--i18nFile=./locale/messages.fr.xlf --locale=fr --i18nFormat=xlf`

**Comment by jolly-roger** [comment]
Hi,
Currently there isn't such a possibility, but if changes of my PR already included into Angular compile there is way to implement such options easily. I will check and if they are included I will implement options on this weekend.

**Comment by wartab** [comment]
Since I needed this feature today, I implemented it myself. Check out #6 if you like it

**Comment by jolly-roger** [comment]
Sure. Merged and published. Thanks for contribution.

**Comment by wartab** [comment]
Thanks for the fast reaction 👍
