### ISSUE TITLE
Can I use incremental compilation?

### ISSUE THREAD

**Issue by tonivj5** [jolly-roger/gulp-ngc#7]
In reference to [gulp-typescript](https://github.com/ivogabe/gulp-typescript#incremental-compilation), I would like to implement that or any kind of cache system to gulp and reduce the compilation time when I do `watch`.

Thanks for your wrapper 😄

**Comment by wartab** [comment]
How do you do incremental compilation with NGC, even without gulp-ngc?

**Comment by tonivj5** [comment]
I don't know, I haven't done with NGC, but how it's a wrapper of tsc... I'm interested in know if it's possible or not (or I can use other tool to reach this)

**Comment by jolly-roger** [comment]
Neither tsc nor ngc and respectively nor gulp-ngc aren't support incremental compilation they even doesn't support piping.

**Comment by tonivj5** [comment]
You are rigth. I have searching info about that and I have found this:
- https://github.com/ivogabe/gulp-typescript/issues/392#issuecomment-239866347 (explanation about gulp-typescript's incremental compilation)
- https://github.com/Microsoft/TypeScript/issues/10879 (https://github.com/Microsoft/TypeScript/issues/10879#issuecomment-248077719) Issue about optimize the build time

Thanks!
